organization = "TS"
environment = "Dev"
app = "ADO"
tier = "Web"
rgname = "RG1"
loc ="East US"
vnet_name = "Vnet1"
vnet_address = ["11.0.0.0/16"]
subnet_name = "subnet01"
subnet_address = ["11.0.0.0/24"]
nic = "NIC"
pip = "pip1"
NSG = "NSG1"
vmname = "VM1"
tagging = {
    CreatedBy = "TrustedSavvy Team"
    CostCenter = 123
    Org = "TS"
}